[package]
name = "word-condenser-standalone" # replace-me
version = "0.2.0" # replace-me -- Choose wisely, see "Note on Versioning" in README
description = "Holochain App to collectively condense latent [term that yet needs to be condensed] dissolved in the grammatical space of human collectives."
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]

###### bump holochain dependencies here
holochain_client = { git = "https://github.com/matthme/holochain-client-rust/", branch = "holochain-0.2.3-beta-rc.1" }
holochain = { version = "0.2.3-beta-rc.1", features = ["sqlite-encrypted"] }
holochain_keystore = "0.2.3-beta-rc.0"
holochain_types = "0.2.3-beta-rc.0"
holochain_zome_types = "0.2.3-beta-rc.0"
mr_bundle = "0.2.2"
######

either = "*"
futures = "0.3"
log = "0.4.14"
log4rs = "1.0.0"
nanoid = "0.4.0"
opener = "0.5.0"
portpicker = "0.1.1"
semver = "1.0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
sodoken = "0.0.9"
symlink = "0.1.0"
tauri = { version = "1.5", features = [ "updater", "devtools", "cli", "clipboard-write-text", "dialog", "process-command-api", "system-tray", "shell-open"] }
thiserror = "1"
url = "2.3.1"
url2 = "0.0.6"
uuid = "0.1.4"

tauri-plugin-deep-link = "0.1"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
